### ISSUE TITLE
Crestron component doesn't load - missing version key

### ISSUE THREAD

**Issue by kfiducia** [npope/home-assistant-crestron-component#3]
"The custom integration 'crestron' does not have a valid version key (None) in the manifest file and was blocked from loading. See https://developers.home-assistant.io/blog/2021/01/29/custom-integration-changes#versions for more details"

"The version key is required from Home Assistant version 2021.6"

This cost me a couple hours of frustration.

Just add a version key in the manifest.json and it will load properly

**Comment by npope** [comment]
Updated the manifest.json starting with version 0.2.4

**Comment by npope** [comment]
Updated the manifest.json with the correct key starting with version 0.2.4
